blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask a question
    url: https://github.com/darkbasic/mikro-orm-dataloaders/discussions
    about: Ask questions and discuss with other community members
